language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install .[dev]
script:
  - pipdeptree
  - coverage run --source=jixin -m pytest
  - coverage report -m
  #- mypy jixin
